#!/bin/bash

function cd(){
	# If "cd" is successful and has an effect
	if \
		local new_directory="$(builtin cd "$@" && builtin pwd)" &&
		[ "$new_directory" != "$(builtin pwd)" ];
	then
		if \
			builtin dirs -l +1 >/dev/null 2>&1 &&
			[ "$(builtin cd "$(dirs -l +1)" && builtin pwd)" = "${new_directory}" ];
		then
			builtin popd +1 -n >/dev/null 2>&1
		fi

		builtin pushd "${new_directory}" >/dev/null 2>&1
	fi
}

function back(){
	local num="$1"
	[ -z "$1" ] && num="1"
	builtin dirs -l +"$num" >/dev/null 2>&1 && cd "$(builtin dirs -l +"$num")"
}
