#!/bin/bash
__dirvar_keys=()
__dirvars=()
function bashrc.d_dirvar_poke(){
	local section=
	local var=
	local val=

	if [ $# -eq 2 ]; then
		var="$1"
		val="$2"
	else
		section="$1"
		var="$2"
		val="$3"
	fi

	local offset="$(bashrc.d_dirvar_peek-offset "$section" "$var")"
	[ -z "$offset" ] && offset="${#__dirvar_keys[@]}"

	__dirvar_keys[$offset]="$section // $var"
	__dirvars[$offset]="$val"
	return 0
}

function bashrc.d_dirvar_peek-offset(){
	local section="$1"
	local var="$2"
	local i=0;
	while [ $i -lt ${#__dirvar_keys[@]} ]; do
		if [ "${__dirvar_keys[$i]}" = "$section // $var" ]; then
			echo "$i"
			return 0
		fi
		i=$(( $i + 1 ))
	done
	return 1
}

function bashrc.d_dirvar_peek(){
	local section=
	local var=

	if [ $# -eq 1 ]; then
		var="$1"
	else
		section="$1"
		var="$2"
	fi

	local i="$(bashrc.d_dirvar_peek-offset "$section" "$var")"

	[ -z "$i" ] && return 1
	echo "${__dirvars[$i]}"
	return 0
}

function bashrc.d_dirvar_-strip(){
	local var="$1"
	while [ "$var" != "${var//\/\///}" ]; do
		var="${var//\/\///}"
	done

	echo "$var"
	return 0
}

function bashrc.d_dirvar_expand(){
	local unexpanded=
	local section=

	if [ $# -eq 2 ]; then
		section="$1"
		unexpanded="$2"
	else
		unexpanded="$1"
	fi

	unexpanded="${unexpanded/#~/$HOME}"
	if [ "$unexpanded" = "${unexpanded/$/}" ]; then
		bashrc.d_dirvar_-strip "$unexpanded"
		return 0
	fi

	local expand="${unexpanded#*$}"
	expand="${expand%%/*}"
	expand="${expand%%.*}"
	expand="${expand%% *}"
	expand="${expand%%	*}"

	if [ -z "$section" ]; then
		expanded="$(bashrc.d_dirvar_peek "$expand")"
	else
		expanded="$(bashrc.d_dirvar_peek "$section" "$expand" || bashrc.d_dirvar_peek "" "$expand")"
	fi
	expand="\$$expand"
	expanded="${unexpanded/$expand/$expanded}"
	bashrc.d_dirvar_-strip "$expanded"
	return 0
}

function bashrc.d_dirvar_list-sections(){
	local i=0;
	local candidate=
	local previous=
	local pwd="$(pwd)"
	printf '\0'
	while [ $i -lt ${#__dirvar_keys[@]} ]; do
		candidate="${__dirvar_keys[$i]% //*}"
		if [ "$candidate" != "$previous" ]; then
			if [ "$pwd" = "$candidate" -o "${pwd#$candidate\/}" != "$pwd" ]; then
				printf '%s\0' "$candidate"
			fi
			previous="$candidate"
		fi
		i=$(( $i + 1 ))
	done

	return 0
}

function bashrc.d_dirvar_parse-ini(){
	local ini="$1"
	local section=
	local line=
	local var=
	local val=
	local oldval=

	while read line; do
		[ -z "$line" ] && continue;
		[ "$line" != "${line#;}" ] && continue;

		if [ "$line" != "${line#[}" -a "$line" != "${line%]}" ]; then
			section="${line#[}"
			section="${section%]}"

			[ "$section" = "global" ] && section=''
			section="$(bashrc.d_dirvar_expand "$section")"
			continue
		fi

		if [ "$line" != "${line/=/}" ]; then
			var="${line%%=*}"
			val="${line#*=}"
			val="$(bashrc.d_dirvar_expand "$section" "$val")"

			if [ "${var#\?}" != "$var" ]; then
				var="${var#\?}"
				[ ! -d "$val" ] && continue
			fi
			if [ "${var#!}" != "$var" ]; then
				var="${var#!}"
				if [ -z "$section" ]; then
					oldval="$(bashrc.d_dirvar_peek "$var")"
				else
					oldval="$(bashrc.d_dirvar_peek "$section" "$var" || bashrc.d_dirvar_peek "$var")"
				fi
				[ -n "$oldval" -a -d "$oldval" ] && continue
			fi
			if [ "${var#\?}" != "$var" ]; then
				var="${var#\?}"
				[ ! -d "$val" ] && continue
			fi

			bashrc.d_dirvar_poke "$section" "$var" "$val"
			continue
		fi
	done < <(
		sed \
			-e 's/^\s*//;s/\s*$//;/^$/d' \
			-e '/^\[.*\]$/{ s/^\[\s*/[/;s/\s*\]$/]/; }' \
			-e '/^\[.*\]$/!{ s/\s*=\s*/=/; }' \
			"$ini"
	)
}

__current_dirvar_section="//NOSECTION//"
function bashrc.d_dirvar_active-section(){
	git help >/dev/null 2>&1 && git="$(git rev-parse --git-dir 2>/dev/null)"

	local dirvar_section
	while read -d $'\0' -r dirvar_section; do
		[ "$__current_dirvar_section" = "$dirvar_section" ] && continue
		__current_dirvar_section="$dirvar_section"

		local dirvar_key
		local dirvar_var
		local dirvar_val
		local dirvar_esc="'\''"
		local dirvar_i=0

		while [ $dirvar_i -lt ${#__dirvar_keys[@]} ]; do
			dirvar_key="${__dirvar_keys[$dirvar_i]}"
			if [ "${dirvar_key%% // *}" = "$dirvar_section" -o "${dirvar_key%% // *}" = "" ]; then
				dirvar_var="${dirvar_key#* // }"
				dirvar_val="${__dirvars[$dirvar_i]}"
				dirvar_val="${dirvar_val//\'/$dirvar_esc}"
				eval "${dirvar_var}='${dirvar_val}'"
			fi
			dirvar_i=$(( $dirvar_i + 1 ))
		done
	done < <(bashrc.d_dirvar_list-sections)
	return 0
}

function bashrc.d_dirvar_reparse(){
	__dirvar_keys=()
	__dirvars=()
	[ -r /etc/dirvars ] && bashrc.d_dirvar_parse-ini /etc/dirvars
	[ -r ~/.dirvars ] && bashrc.d_dirvar_parse-ini ~/.dirvars
}

bashrc.d prompt-command poke dirvar bashrc.d_dirvar_active-section
bashrc.d_dirvar_reparse
